name: Security and Notify Workflow

on:
  - push
  - workflow_dispatch
    
jobs:
  security_check:
    runs-on: ubuntu-latest
    name: Run Security Check
    outputs:
      log_content: ${{ steps.read_log.outputs.log }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Security Check
        uses: ./.github/actions/security-check
        with:
          python_file: "app.py"
          log_file: "security.log"

      - name: Read Log File Content
        id: read_log
        run: |
          LOG=$(cat security.log | base64)
          echo "log=$LOG" >> $GITHUB_OUTPUT

  notify_owner:
    needs: security_check
    runs-on: ubuntu-latest
    name: Notify Owner via Email
    steps:
      - name: Decode and Save Log
        run: |
          echo "${{ needs.security_check.outputs.log_content }}" | base64 --decode > security.log

      - name: Send Email (Notify)
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Security Scan Report
          to: ${{ github.event.repository.owner.email }}
          from: GitHub Security Bot
          body: |
            Hello,

            Please find the attached security scan report from the latest push.

          attachments: security.log
