name: Security and Notify Workflow

on:
  - workflow_dispatch
    
jobs:
  security_check:
    runs-on: ubuntu-latest
    name: Run Security Check
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Security Check
        uses: ./.github/actions/security-check
        with:
          python_file: "app/calculator.py"
          log_file: "security.log"

      - name: Upload Security Log
        uses: actions/upload-artifact@v4
        with:
          name: security-log
          path: security.log

  notify_owner:
    needs: security_check
    runs-on: ubuntu-latest
    name: Notify Owner via Email
    steps:
      - name: Decode and Save Log
        run: |
          echo "${{ needs.security_check.outputs.log_content }}" | base64 --decode > security.log

      - name: Send Email (Notify)
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Security Scan Report
          to: ${{ github.event.repository.owner.email }}
          from: GitHub Security Bot
          body: |
            Hello,

            Please find the attached security scan report from the latest push.

          attachments: security.log
