name: python test
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: install python
        uses: actions/setup-python@v5.6.0
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: |
          PYTHONPATH=./ pytest tests/
